# Supabase Local Development Configuration

[project]
name = "toacc-gallery"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/checkout"]
jwt_expiry = 3600
enable_signup = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true
port = 4000

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions]
enabled = true
verify_jwt = false

