/**
 * Comprehensive artwork collection for Shop and Gallery pages
 * Includes artworks from homepage and all new additions
 */

export interface Artwork {
  id: string;
  title: string;
  artist: string;
  year: number;
  medium: string;
  dimensions: string;
  price: number;
  category: string;
  image: string;
  description: string;
  story?: string; // Extended story/description for artworks with detailed narratives
  available: boolean;
  featured?: boolean;
}

// Placeholder description for artworks without stories
const PLACEHOLDER_DESCRIPTION = 'Artwork description coming soon. This piece showcases the artist\'s unique creative vision and technical mastery. Detailed information will be available shortly.';

/**
 * All artworks collection
 * Includes artworks from homepage and new additions
 */
export const allArtworks: Artwork[] = [
  // New artworks from user input
  {
    id: 'bone-of-contention',
    title: 'Bone of Contention?',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Beaded Batik Quilt Tapestry',
    dimensions: '47 x 32"',
    price: 17850000,
    category: 'Batik',
    image: '/Assets/bone-of-contention.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'old-fashion-trendy',
    title: 'Old Fashion Trendy',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Beaded Batik Quilt Tapestry on Corduroy',
    dimensions: '58 x 48"',
    price: 14250000,
    category: 'Batik',
    image: '/Assets/old-fashion-trendy.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'natures-own-making',
    title: 'Nature\'s Own Making; Return to the Source',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik',
    dimensions: '63 x 86"',
    price: 10425000,
    category: 'Batik',
    image: '/Assets/nature-lg.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'the-basketballer',
    title: 'The Basketballer',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Beaded Batik Quilt Tapestry',
    dimensions: '60 x 18"',
    price: 44425000,
    category: 'Batik',
    image: '/Assets/basketball-lg.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'faceless-entertainer',
    title: 'Faceless Entertainer',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Beaded Batik Quilt Tapestry',
    dimensions: '74 x 21"',
    price: 10350000,
    category: 'Batik',
    image: '/Assets/faceless-lg.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'the-philosopher',
    title: 'The Philosopher',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Beaded Batik Quilt Tapestry on Hand Made Paper',
    dimensions: '59 x 18"',
    price: 8625000,
    category: 'Batik',
    image: '/Assets/philosopher-lg.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'inter-connectivity',
    title: 'Inter-Connectivity',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Beads on Velvet',
    dimensions: '70 x 48"',
    price: 9000000,
    category: 'Mixed Media',
    image: '/Assets/interactivity.jpg',
    description: 'This piece depicts the way our world interconnects. We are all interdependent in spite of our individual differences. Therefore, there can only be one race and that is the Human Race.',
    story: 'This piece depicts the way our world interconnects. We are all interdependent in spite of our individual differences. Therefore, there can only be one race and that is the Human Race.',
    available: true,
    featured: true,
  },
  {
    id: 'interlude',
    title: 'Interlude',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik Quilt Tapestry',
    dimensions: '68 x 45"',
    price: 6000000,
    category: 'Batik',
    image: '/Assets/interlude.jpg',
    description: 'Interlude is simply depicting the moments of our life when we cross one moment of life to another. The keyword here is: Do we take adequate record of the transition of our life?',
    story: 'Interlude is simply depicting the moments of our life when we cross one moment of life to another. The keyword here is: Do we take adequate record of the transition of our life?',
    available: true,
    featured: false,
  },
  {
    id: 'bits-and-pieces',
    title: 'Bits and Pieces',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik Quilt Tapestry',
    dimensions: '78 x 50"',
    price: 10000000,
    category: 'Batik',
    image: '/Assets/bits_and_pieces.jpg',
    description: 'Bits and Pieces depicts the importance of how little pieces of our life can come together and make a whole. As the saying "The difference between being good and being great is how much attention you pay to details" also little drops of water makes a mighty ocean.',
    story: 'Bits and Pieces depicts the importance of how little pieces of our life can come together and make a whole. As the saying "The difference between being good and being great is how much attention you pay to details" also little drops of water makes a mighty ocean.',
    available: true,
    featured: false,
  },
  {
    id: 'between-haves-have-nots',
    title: 'Between the Haves and the Have Nots',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik',
    dimensions: '58 x 67"',
    price: 3750000,
    category: 'Batik',
    image: '/Assets/between.jpg',
    description: 'The disparity between the haves and have nots will forever be a challenge that we must deal with. Like the Yoruba proverb which says "Fingers are not equal," it doesn\'t matter what all of us can\'t have; but those who have must learn to share, so the gap gets smaller and smaller. After all, to give does not mean to lack.',
    story: 'The disparity between the haves and have nots will forever be a challenge that we must deal with. Like the Yoruba proverb which says "Fingers are not equal," it doesn\'t matter what all of us can\'t have; but those who have must learn to share, so the gap gets smaller and smaller. After all, to give does not mean to lack.',
    available: true,
    featured: false,
  },
  {
    id: 'inner-part-masquerade',
    title: 'Inner Part of the Masquerade',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik Quilt Tapestry',
    dimensions: '71 x 63"',
    price: 7425000,
    category: 'Batik',
    image: '/Assets/masquerade.jpg',
    description: 'Masquerade is the representation of the ancestors according to the Yoruba People across the length and breadth of the world. Masquerade festivity is observed in honor of the past ancestors. The message here is the inner part of that masquerade, masquerade costumes become more elaborate over time, as more and more beautiful fabrics are added to document the masquerade history. This is the viewer\'s opportunity to see the behind the scenes story of the costumes of the masquerade.',
    story: 'Masquerade is the representation of the ancestors according to the Yoruba People across the length and breadth of the world. Masquerade festivity is observed in honor of the past ancestors. The message here is the inner part of that masquerade, masquerade costumes become more elaborate over time, as more and more beautiful fabrics are added to document the masquerade history. This is the viewer\'s opportunity to see the behind the scenes story of the costumes of the masquerade.',
    available: true,
    featured: true,
  },
  {
    id: 'treasure-buried-earth',
    title: 'Treasure Buried Under the Earth',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik Quilt Tapestry',
    dimensions: '68 x 59"',
    price: 750000,
    category: 'Batik',
    image: '/Assets/treasure.jpg',
    description: 'I look around and see all the development and wonder where it all comes from; the simple answer is that it comes from the earth. All sorts of mineral resources come from under the earth. The need to take care of our environment becomes imperative. Man being an explorer always forgets that how you treat your environment is how your environment will treat you.',
    story: 'I look around and see all the development and wonder where it all comes from; the simple answer is that it comes from the earth. All sorts of mineral resources come from under the earth. The need to take care of our environment becomes imperative. Man being an explorer always forgets that how you treat your environment is how your environment will treat you.',
    available: true,
    featured: false,
  },
  {
    id: 'argungu-fishing-festival',
    title: 'Argungu Fishing Festival',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Linocut',
    dimensions: '22 x 30"',
    price: 2250000,
    category: 'Print',
    image: '/Assets/argungun.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'abstract',
    title: 'Abstract',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Batik Quilt Tapestry',
    dimensions: '60 x 30"',
    price: 4275000,
    category: 'Batik',
    image: '/Assets/abstract.jpg',
    description: 'Abstract is an escape route for every individual to have the freedom of making up their own story. However, the artist here refers to the Stars of Moses and the empathy of the Jewish and other people around the world. To forgive is to move on, whereas to forget is to lose track of history and for it to repeat itself.',
    story: 'Abstract is an escape route for every individual to have the freedom of making up their own story. However, the artist here refers to the Stars of Moses and the empathy of the Jewish and other people around the world. To forgive is to move on, whereas to forget is to lose track of history and for it to repeat itself.',
    available: true,
    featured: false,
  },
  {
    id: 'yoruba-bata-drummers',
    title: 'Yoruba Bata Drummers',
    artist: 'Tunde Odunlade',
    year: 2024,
    medium: 'Linocut',
    dimensions: '30 x 22"',
    price: 2250000,
    category: 'Print',
    image: '/Assets/Yoruba_Bata_Drummers.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'the-native-doctor',
    title: 'The Native Doctor',
    artist: 'Yinka Adeyemi',
    year: 2005,
    medium: 'Beads on Board',
    dimensions: '48 x 32"',
    price: 8000000,
    category: 'Mixed Media',
    image: '/Assets/native_doctor.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  // Other artists' works
  {
    id: 'mask',
    title: 'Mask',
    artist: 'Akinleye Ademola',
    year: 2022,
    medium: 'Collage',
    dimensions: '37 x 21"',
    price: 650000,
    category: 'Collage',
    image: '/Assets/hero6.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'market-women',
    title: 'Market Women',
    artist: 'Kayode Shosan',
    year: 2024,
    medium: 'Acrylic on Canvas',
    dimensions: '48 x 46"',
    price: 850000,
    category: 'Painting',
    image: '/Assets/market_women.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'butterfly',
    title: 'Butterfly',
    artist: 'Olaniyi Odunsin',
    year: 2024,
    medium: 'Acrylic on Canvas',
    dimensions: '36 x 36"',
    price: 800000,
    category: 'Painting',
    image: '/Assets/hero4.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'fatherly-love',
    title: 'Fatherly Love',
    artist: 'Musibaudeen Baaki',
    year: 2025,
    medium: 'Acrylic on Canvas',
    dimensions: '48 x 36"',
    price: 500000,
    category: 'Painting',
    image: '/Assets/fatherly_love.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'leadership',
    title: 'Leadership',
    artist: 'Rufus Ogundele',
    year: 1998,
    medium: 'Oil on Board',
    dimensions: 'N/A',
    price: 7500000,
    category: 'Painting',
    image: '/Assets/leadership.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'the-missing-link',
    title: 'The Missing Link',
    artist: 'Inioluwa Akinnola',
    year: 2025,
    medium: 'Embroidery',
    dimensions: 'N/A',
    price: 350000,
    category: 'Textile',
    image: '/Assets/hero 4.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'football',
    title: 'Football',
    artist: 'Ademola Akintola',
    year: 2023,
    medium: 'Metal Foil Relief',
    dimensions: 'N/A',
    price: 5000000,
    category: 'Sculpture',
    image: '/Assets/football.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'petals-of-resilience',
    title: 'Petals of Resilience',
    artist: 'Ogundele Ademidun',
    year: 2025,
    medium: 'Acrylic on Canvas',
    dimensions: '36 x 36"',
    price: 350000,
    category: 'Painting',
    image: '/Assets/petals.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'heal-our-nation',
    title: 'Heal Our Nation',
    artist: 'Emi Art',
    year: 2024,
    medium: 'Acrylic on Canvas',
    dimensions: 'N/A',
    price: 250000,
    category: 'Painting',
    image: '/Assets/heal.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'dove-lady',
    title: 'Dove Lady',
    artist: 'Adetona Solomon',
    year: 2021,
    medium: 'Acrylic on Canvas',
    dimensions: 'N/A',
    price: 850000,
    category: 'Painting',
    image: '/Assets/dove.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'onibata',
    title: 'Onibata',
    artist: 'Emi Art',
    year: 2025,
    medium: 'Acrylic on Canvas',
    dimensions: 'N/A',
    price: 350000,
    category: 'Painting',
    image: '/Assets/onibata.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'fura-maid',
    title: 'Fura Maid',
    artist: 'Olumide Fatoba',
    year: 2024,
    medium: 'Acrylic on Canvas',
    dimensions: '53 x 41"',
    price: 1200000,
    category: 'Painting',
    image: '/Assets/fura.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  // Artworks from homepage (ShopPreview)
  {
    id: 'cavalcade-of-stars',
    title: 'Cavalcade of Stars',
    artist: 'Prince Tunde Odunlade',
    year: 2024,
    medium: 'Batik',
    dimensions: 'N/A',
    price: 12500000,
    category: 'Batik',
    image: '/Assets/Cavalcade of Stars.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'close-to-my-heart',
    title: 'Close to My Heart',
    artist: 'Eugene Ugoji',
    year: 2021,
    medium: 'Mixed Media',
    dimensions: 'N/A',
    price: 850000,
    category: 'Mixed Media',
    image: '/Assets/close to my heart.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'searching-for-knowledge',
    title: 'Searching for Knowledge',
    artist: 'Toh-mie',
    year: 2023,
    medium: 'Mixed Media',
    dimensions: 'N/A',
    price: 400000,
    category: 'Mixed Media',
    image: '/Assets/searching for knowledge.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'melody-maker',
    title: 'Melody Maker',
    artist: 'Adeniyi Dagunro',
    year: 2021,
    medium: 'Mixed Media',
    dimensions: '32 x 19',
    price: 800000,
    category: 'Mixed Media',
    image: '/Assets/hero10.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  // Additional artworks from existing shop/gallery pages
  
  {
    id: 'happy-mother-and-child',
    title: 'Happy Mother and Child',
    artist: 'Israel Taiwo',
    year: 2024,
    medium: 'Acrylic on Canvas',
    dimensions: 'N/A',
    price: 1500000,
    category: 'Painting',
    image: '/Assets/hero2.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: true,
  },
  {
    id: 'head',
    title: 'Head',
    artist: 'Toh-mie',
    year: 2024,
    medium: 'Acrylic on Canvas',
    dimensions: 'N/A',
    price: 600000,
    category: 'Painting',
    image: '/Assets/hero3.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
  {
    id: 'market-stories',
    title: 'Market Stories',
    artist: 'Emerging Artist',
    year: 2024,
    medium: 'Oil on Canvas',
    dimensions: '30" x 40"',
    price: 285000,
    category: 'Painting',
    image: '/Assets/featured1.jpg',
    description: 'Vivid portrayal of daily life in Nigerian markets, celebrating community and commerce through bold brushstrokes.',
    available: true,
    featured: false,
  },
  {
    id: 'textile-dreams',
    title: 'Textile Dreams',
    artist: 'Adire Master',
    year: 2024,
    medium: 'Adire Textile',
    dimensions: '36" x 36"',
    price: 340000,
    category: 'Textile',
    image: '/Assets/featured2.jpg',
    description: PLACEHOLDER_DESCRIPTION,
    available: true,
    featured: false,
  },
];

